### ISSUE TITLE
Test suite fails with Mojolicious 6.0

### ISSUE THREAD

**Issue by eserte** [sshaw/Mojolicious-Plugin-ParamExpand#2]
See http://www.cpantesters.org/cpan/report/cd98967a-6c4e-1014-9522-f409a5c74da1 for a sample fail report --- more will be available at http://matrix.cpantesters.org/?dist=Mojolicious-Plugin-ParamExpand%200.02 in a few hours.

**Comment by sshaw** [comment]
Failing test cases for multiple Mojolicious plugins? Must be another release with braking changes. 

So is the life of a plugin maintainer...

**Comment by sshaw** [comment]
Fixed on c6f3d7adf84b0d5f736c5d692032dff507be1078
