### ISSUE TITLE
Windows PPM contains conflicting README.html

### ISSUE THREAD

**Issue by sierracc** [sshaw/Mojolicious-Plugin-ParamExpand#3]
Hi,

the 0.02 Windows PPM package available from ActiveState contains a README.html conflicting with another README.html. As far as I can see, the README.pod is converted to README.html during the PPM generation process and placed in the Mojolicious main plugins directory, conflicting with other files there.

Below is a copy of the error within the ActiveState Perl Package Manager when installing ParamExpand:

Synchronizing Database done
Mojolicious-Plugin-ParamExpand marked for install
Installing package ... 
  Downloading Mojolicious-Plugin-ParamExpand-0.02 ... done
  Unpacking Mojolicious-Plugin-ParamExpand-0.02 ... done
  Generating HTML for Mojolicious-Plugin-ParamExpand-0.02 ... done
  Updating files in site area ... failed
Installing package failed

ERROR: File conflict for 'C:/Perl64/html/site/lib/Mojolicious/Plugin/README.html'.
    The package Mojolicious-Plugin-RenderFile has already installed a file that package Mojolicious-Plugin-ParamExpand
    wants to install.

Yours,
André

**Comment by sshaw** [comment]
Oooh, PPM. 

I was skipping README.pod -something that I explicitly created. Interesting that it installs an HTML file too. 

You should open a similar issue on `Mojolicious::Plugin::RenderFile`, as it [doesn't skip installing the README](https://github.com/sshaw/Mojolicious-Plugin-ParamExpand/blob/master/INSTALL.SKIP).

**Comment by sshaw** [comment]
I'll do a new release tonight. Need to resolve #2 too.

**Comment by sierracc** [comment]
> You should open a similar issue on Mojolicious::Plugin::RenderFile

Done so: https://github.com/koorchik/Mojolicious-Plugin-RenderFile/issues/12

**Comment by sshaw** [comment]
@sierracc so looks like PPM does not respect `INSTALL.SKIP` and will always defer to the local PPM settings. 

In `ppm`, line 1381:

```perl
# $ppm is  ActivePerl::PPM::Client
my $summary = $ppm->install(packages => \@_, area => $area, force => $force);
```

In  `ActivePerl::PPM::Client`:
```perl
# Line 1284
my $install_html = $args{install_html};
$install_html = $self->config_get('install_html') unless defined $install_html;
$install_html = 1 unless defined $install_html;
$install_html &&= eval { require ActivePerl::DocTools; };
```

`config_get` queries the local SQLite DB. 

Suggestions? I thought I heard somewhere that ActiveState was not going to get out of the Perl build business, but I can't find anything about that...

**Comment by thrig** [comment]
Hmm, perhaps there is a knob to turn off the POD -> HTML generation? If so, that could be a kluge-a-round to this problem.

**Comment by sshaw** [comment]
> Hmm, perhaps there is a knob to turn off the POD -> HTML generation?

Yes, it's this: 

```
C:\> ppm config install_html 0
```
